trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
- group: VeracodeIaC

steps:
- script: |
    curl -fsS https://tools.veracode.com/veracode-cli/install | sh
  displayName: 'Configuração inicial'

- task: CmdLine@2
  inputs:
    script: './veracode scan --source ./terraform --type directory --format text'
  displayName: 'Scan'

- task: CmdLine@2
  inputs:
    script: './veracode sbom --source ./terraform --type directory --format text'
  displayName: 'SBOM'